=== r4nc0r/grommunio-web/server/manifest.dtd
<!-- The <plugin> element. This is the root element for the document -->
<!ELEMENT plugin (info,config?,dependencies?,optional?,translations?,components)>

	<!-- The <info> element. Positioned inside the <plugin> and/or <component> elements. Provides meta information -->
	<!ELEMENT info (version?,name,title?,author?,authorURL?,description?)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT authorURL (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

	<!-- The <config> element. Positioned inside the <plugin> element. Provides the location of the configuration file(s) -->
	<!ELEMENT config (configfile+)>
		<!ELEMENT configfile (#PCDATA)>

	<!-- The <dependencies> element. Positioned inside the <plugin> element. Provides the plugin dependencies -->
	<!ELEMENT dependencies (depends+)>
		<!ELEMENT depends (dependsname)>
			<!ELEMENT dependsname (#PCDATA)>

	<!-- The <optional> element. Positioned inside the <plugin> element. Declares that users can switch the plugin off in their settings; its client and resource files are then only sent to users who have it enabled. Plugins depending on an unloaded plugin are not loaded either -->
	<!ELEMENT optional EMPTY>

	<!-- The <translations> element. Positioned inside the <plugin> element. Provides the translations information -->
	<!ELEMENT translations (translationsdir+)>
		<!ELEMENT translationsdir (#PCDATA)>

	<!-- The <components> element. Positioned inside the <plugin> element. Provides the components -->
	<!ELEMENT components (component+)>
		<!ELEMENT component (info?,files)>
			<!ELEMENT files (server?,client?,resources?)>
				<!ELEMENT server (serverfile+)>
					<!ELEMENT serverfile (#PCDATA)>
				<!ELEMENT client (clientfile+)>
					<!ELEMENT clientfile (#PCDATA)>
				<!ELEMENT resources (resourcefile+)>
					<!ELEMENT resourcefile (#PCDATA)>

<!-- The attributes for the <plugin> element. -->
<!ATTLIST plugin version CDATA #REQUIRED>

<!-- The attributes for the <optional> element. The switch is the setting zarafa/v1/plugins/<settingsname>/enable, settingsname defaults to the plugin directory -->
<!ATTLIST optional settingsname CDATA #IMPLIED>

<!-- The attributes for the <depends> element. -->
<!ATTLIST depends type (depends|requires|recommends|suggests) "depends">

<!-- The attributes for the <serverfile> element. -->
<!ATTLIST serverfile load (release|debug|source) "release">
<!ATTLIST serverfile type (plugin|module|notifier) "plugin">
<!ATTLIST serverfile module CDATA #IMPLIED> 
<!ATTLIST serverfile notifier CDATA #IMPLIED> 

<!-- The attributes for the <clientfile> element. -->
<!ATTLIST clientfile load (release|debug|source) "release">

<!-- The attributes for the <resourcefile> element. -->
<!ATTLIST resourcefile load (release|debug|source) "release">

=== r4nc0r/grommunio-web/plugins/smime/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>2.0</version>
		<name>S/MIME Plugin</name>
		<title>S/MIME Plugin</title>
		<author>grommunio</author>
		<authorURL>https://www.grommunio.com</authorURL>
		<description>Enables S/MIME Integration in grommunio web</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<translations>
		<translationsdir>language</translationsdir>
	</translations>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.smime.php</serverfile>
					<serverfile type="module" module="pluginsmimemodule">php/class.pluginsmimemodule.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/smime.js</clientfile>
					<clientfile load="debug">js/smime-debug.js</clientfile>
					<clientfile load="source">js/SmimePlugin.js</clientfile>
					<clientfile load="source">js/SmimeText.js</clientfile>
					<clientfile load="source">js/data/SmimeAttachmentRecord.js</clientfile>
					<clientfile load="source">js/data/SmimeAttachmentStore.js</clientfile>
					<clientfile load="source">js/data/SmimeCertificateRecord.js</clientfile>
					<!-- CertificateStore -->
					<clientfile load="source">js/data/JsonCertificateReader.js</clientfile>
					<clientfile load="source">js/data/SmimeCertificateStore.js</clientfile>

					<clientfile load="source">js/data/SmimeResponseHandler.js</clientfile>
					<clientfile load="source">js/ui/Viewport.js</clientfile>
					<clientfile load="source">js/ui/FormPanel.js</clientfile>
					<clientfile load="source">js/dialogs/PassphraseContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/PassphraseWindow.js</clientfile>
					<clientfile load="source">js/dialogs/ChangePassphraseContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/ChangePassphrasePanel.js</clientfile>
					<clientfile load="source">js/settings/SettingsSmimeCategory.js</clientfile>
					<clientfile load="source">js/settings/SettingsSmimeWidget.js</clientfile>
					<clientfile load="source">js/settings/UploadCertificateWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsPublickeyWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsPublickeyPanel.js</clientfile>
					<clientfile load="source">js/settings/SettingsPublickeyGrid.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/smime.css</resourcefile>
					<resourcefile load="source">resources/css/smime-styles.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/kendox/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>3.1</version>
		<name>kendox</name>
		<title>Kendox InfoShare plugin</title>
		<author>grommunio GmbH</author>
		<authorURL>http://www.grommunio.com</authorURL>
		<description>Archiving emails to Kendox Infoshare system</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<components>
		<component>
			<files>
				<server>
					<serverfile type="module" module="kendoxmodule">php/class.kendox-module.php</serverfile>				
					<serverfile>php/plugin.kendox.php</serverfile>
				</server>
				<client>
					<clientfile load="debug">js/kendox-debug.js</clientfile>
					<clientfile load="release">js/kendox.js</clientfile>
					<clientfile load="source">js/kendox-plugin.js</clientfile>
					<clientfile load="source">js/kendox-settings.js</clientfile>	
					<clientfile load="source">js/kendox-upload-dialog.js</clientfile>
				</client>
				<resources>
					<resourcefile load="debug">resources/kendox.css</resourcefile>
					<resourcefile load="release">resources/kendox.css</resourcefile>
					<resourcefile load="source">resources/kendox.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/meet/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.0</version>
		<name>meet</name>
		<title>Meet</title>
		<author>grommunio</author>
		<authorURL>https://grommunio.com</authorURL>
		<description>Support for grommunio Meet</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/settings.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/meet.js</clientfile>
					<clientfile load="debug">js/meet-debug.js</clientfile>
					<clientfile load="source">js/plugin.js</clientfile>
					<clientfile load="source">js/settings.js</clientfile>
					<clientfile load="source">js/tabpanel.js</clientfile>
					<clientfile load="source">js/addmeetingdialog.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/meet.css</resourcefile>
					<resourcefile load="debug">resources/css/meet.css</resourcefile>
					<resourcefile load="source">resources/css/meet.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/desktopnotifications/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.1</version>
		<name>desktopnotifications</name>
		<title>Desktop Notifications Plugin</title>
		<author>grommunio</author>
		<authorURL>https://grommunio.com</authorURL>
		<description>Allow the user to Desktop Notifications for different type of actions</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.desktopnotifications.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/desktopnotifications.js</clientfile>
					<clientfile load="debug">js/desktopnotifications-debug.js</clientfile>
					<clientfile load="source">js/DesktopNotificationsPlugin.js</clientfile>
					<clientfile load="source">js/settings/SettingsNotificationsCategory.js</clientfile>
					<clientfile load="source">js/settings/SettingsNotificationsWidget.js</clientfile>
					<clientfile load="source">js/DesktopNotifications.js</clientfile>
					<clientfile load="source">js/DesktopNotifier.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/desktopnotifications.css</resourcefile>
					<resourcefile load="source">resources/desktopnotifications.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/filesbackendSeafile/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>2.0.69</version>
		<name>filesbackendSeafile</name>
		<title>Files: Seafile Backend</title>
		<author>grommunio</author>
		<authorURL>https://www.grommunio.com</authorURL>
		<description>This backend for Files provides seafile support</description>
	</info>
	<dependencies>
		<depends type="depends">
			<dependsname>files</dependsname>
		</depends>
	</dependencies>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/class.pluginseafile.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/filesbackendSeafile.js</clientfile>
					<clientfile load="debug">js/filesbackendSeafile-debug.js</clientfile>
					<clientfile load="source">src/js/SeafileBackend.js</clientfile>
					<clientfile load="source">src/js/ui/FilesShareDialogPanel.js</clientfile>
					<clientfile load="source">src/js/ui/FilesShareUserEditPanel.js</clientfile>
					<clientfile load="source">src/js/ui/FilesShareUserEditContentPanel.js</clientfile>
					<clientfile load="source">src/js/ui/FilesShareUserGrid.js</clientfile>
					<clientfile load="source">src/js/ui/FilesShareUserGridColumnModel.js</clientfile>
					<clientfile load="source">src/js/ui/UserGroupPredictorField.js</clientfile>
					<clientfile load="source">src/js/data/ShareGridStore.js</clientfile>
					<clientfile load="source">src/js/data/ResponseHandler.js</clientfile>
					<clientfile load="source">src/js/data/ShareGridRecord.js</clientfile>
					<clientfile load="source">src/js/data/singleton/ShareStore.js</clientfile>
					<clientfile load="source">src/js/data/RecipientTypes.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/filesbackendSeafile.css</resourcefile>
					<resourcefile load="debug">resources/css/filesbackendSeafile.css</resourcefile>
					<resourcefile load="source">resources/css/filesbackendSeafile.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/files/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>5.0</version>
		<name>files</name>
		<title>Files Plugin</title>
		<author>grommunio GmbH</author>
		<authorURL>http://www.grommunio.com</authorURL>
		<description>Integrate Files into grommunio web</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<components>
		<component>
			<files>
				<server>
					<serverfile type="module" module="fileslistmodule">php/modules/class.fileslistmodule.php</serverfile>
					<serverfile type="module" module="filesaccountmodule">php/class.filesaccountmodule.php</serverfile>
					<serverfile type="module" module="filesbrowsermodule">php/class.filesbrowsermodule.php</serverfile>
					<serverfile type="module" module="hierarchylistmodule">php/modules/class.hierarchylistmodule.php</serverfile>
					<serverfile type="notifier" notifier="filesbrowsernotifier">php/notifiers/class.filesbrowsernotifier.php</serverfile>
					<serverfile type="notifier" notifier="fileshierarchynotifier">php/notifiers/class.fileshierarchynotifier.php</serverfile>
					<serverfile>php/plugin.files.php</serverfile>
				</server>
				<client>
					<clientfile load="release">php/jsloader.php?debug=false</clientfile>
					<clientfile load="debug">php/jsloader.php?debug=true</clientfile>
					<clientfile load="source">js/FilesContextModel.js</clientfile>
					<clientfile load="source">js/FilesContext.js</clientfile>
					<clientfile load="source">js/FilesPlugin.js</clientfile>
					<clientfile load="source">js/ui/FilesMainContextMenu.js</clientfile>
					<clientfile load="source">js/ui/FilesTreeContextMenu.js</clientfile>
					<clientfile load="source">js/ui/FilesMainPanel.js</clientfile>
					<clientfile load="source">js/ui/FilesPreviewPanel.js</clientfile>
					<clientfile load="source">js/ui/FilesRecordAccountView.js</clientfile>
					<clientfile load="source">js/ui/FilesRecordDetailsPanel.js</clientfile>
					<clientfile load="source">js/ui/FilesRecordGridColumnModel.js</clientfile>
					<clientfile load="source">js/ui/FilesRecordGridView.js</clientfile>
					<clientfile load="source">js/ui/FilesRecordIconView.js</clientfile>
					<clientfile load="source">js/ui/FilesRecordViewPanel.js</clientfile>
					<clientfile load="source">js/ui/FilesListToolbar.js</clientfile>
					<clientfile load="source">js/ui/FilesTopToolbar.js</clientfile>
					<clientfile load="source">js/ui/NavigatorTreePanel.js</clientfile>
					<clientfile load="source">js/ui/FilesHierarchyRootNode.js</clientfile>
					<clientfile load="source">js/ui/FilesFolderNode.js</clientfile>
					<clientfile load="source">js/ui/FilesRootFolderNode.js</clientfile>
					<clientfile load="source">js/ui/FolderNodeUI.js</clientfile>

					<clientfile load="source">js/ui/Tree.js</clientfile>
					<clientfile load="source">js/ui/ContentPanel.js</clientfile>
					<clientfile load="source">js/ui/OnlyofficePanel.js</clientfile>
					<clientfile load="source">js/ui/TreeSorter.js</clientfile>
					<clientfile load="source">js/ui/MultipleFileUploadField.js</clientfile>
					<clientfile load="source">js/ui/UploadComponent.js</clientfile>
					<clientfile load="source">js/ui/dialogs/AttachFromFilesContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/CreateFolderContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/CreateFolderPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/CreateFileContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/CreateFilePanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/AttachFromFilesGridPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/AttachFromFilesPanel.js</clientfile>

					<clientfile load="source">js/ui/dialogs/FilesRecordContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/FilesUploadContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/SaveToFilesContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/SaveToFilesPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/ShareContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/SharePanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/UploadStatusContentPanel.js</clientfile>
					<clientfile load="source">js/ui/dialogs/UploadStatusPanel.js</clientfile>
					<clientfile load="source">js/ui/snippets/FilesQuotaBar.js</clientfile>
					<clientfile load="source">js/ui/snippets/FilesNavigationBar.js</clientfile>
					<clientfile load="source">js/ui/snippets/WebODFPanel.js</clientfile>
					<clientfile load="source">js/ui/snippets/PDFjsPanel.js</clientfile>
					<clientfile load="source">js/settings/SettingsAccountWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsMainCategory.js</clientfile>
					<clientfile load="source">js/settings/SettingsResetWidget.js</clientfile>
					<clientfile load="source">js/settings/data/AccountRenderUtil.js</clientfile>
					<clientfile load="source">js/settings/ui/AccountEditContentPanel.js</clientfile>
					<clientfile load="source">js/settings/ui/AccountEditPanel.js</clientfile>
					<clientfile load="source">js/settings/ui/AccountGrid.js</clientfile>
					<clientfile load="source">js/settings/ui/AccountGridColumnModel.js</clientfile>
					<clientfile load="source">js/settings/ui/AccountPanel.js</clientfile>
					<clientfile load="source">js/settings/ui/FeatureQuotaInfoContentPanel.js</clientfile>
					<clientfile load="source">js/settings/ui/FeatureQuotaInfoPanel.js</clientfile>
					<clientfile load="source">js/settings/ui/FeatureVersionInfoContentPanel.js</clientfile>
					<clientfile load="source">js/settings/ui/FeatureVersionInfoPanel.js</clientfile>

					<clientfile load="source">js/data/FilesFoldersSubStore.js</clientfile>
					<clientfile load="source">js/data/FilesFolderResponseHandler.js</clientfile>
					<clientfile load="source">js/data/FilesHierarchyProxy.js</clientfile>
					<clientfile load="source">js/data/FilesHierarchyStore.js</clientfile>
					<clientfile load="source">js/data/FilesJsonReader.js</clientfile>
					<clientfile load="source">js/data/FilesStoreRecord.js</clientfile>
					<clientfile load="source">js/data/FilesFolderRecord.js</clientfile>

					<clientfile load="source">js/data/FilesShadowProxy.js</clientfile>
					<clientfile load="source">js/data/FilesShadowStore.js</clientfile>

					<clientfile load="source">js/data/AccountRecord.js</clientfile>
					<clientfile load="source">js/data/AccountStore.js</clientfile>
					<clientfile load="source">js/data/FilesBackendRecord.js</clientfile>
					<clientfile load="source">js/data/FilesBackendStore.js</clientfile>
					<clientfile load="source">js/data/Actions.js</clientfile>
					<clientfile load="source">js/data/ComponentBox.js</clientfile>
					<clientfile load="source">js/data/ViewModes.js</clientfile>
					<clientfile load="source">js/data/Views.js</clientfile>
					<clientfile load="source">js/data/DataModes.js</clientfile>
					<clientfile load="source">js/data/FileTypes.js</clientfile>
					<clientfile load="source">js/data/FilesProxy.js</clientfile>
					<clientfile load="source">js/data/FilesRecord.js</clientfile>
					<clientfile load="source">js/data/FilesRecordStore.js</clientfile>
					<clientfile load="source">js/data/NavigatorTreeLoader.js</clientfile>
					<clientfile load="source">js/data/ResponseHandler.js</clientfile>
					<clientfile load="source">js/data/Utils.js</clientfile>
					<clientfile load="source">js/data/AsyncFilesTreeNode.js</clientfile>



					<clientfile load="source">php/jsloader.php?debug=true</clientfile>
				</client>
				<resources>
					<resourcefile load="release">php/cssloader.php?debug=false</resourcefile>
					<resourcefile load="debug">php/cssloader.php?debug=true</resourcefile>
					<resourcefile load="source">php/cssloader.php?debug=true&amp;source=true</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/intranet/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.0</version>
		<name>intranet</name>
		<title>Intranet</title>
		<author>grommunio</author>
		<authorURL>https://grommunio.com</authorURL>
		<description>The intranet plugin adds a button to the top menu bar that opens a webpage inside grommunio Web</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.intranet.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/intranet.js</clientfile>
					<clientfile load="debug">js/intranet-debug.js</clientfile>
					<clientfile load="source">js/IntranetPlugin.js</clientfile>
					<clientfile load="source">js/ui/ContentPanel.js</clientfile>
					<clientfile load="source">js/ui/Panel.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/intranet.css</resourcefile>
					<resourcefile load="debug">resources/css/intranet.css</resourcefile>
					<resourcefile load="source">resources/css/intranet.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== r4nc0r/grommunio-web/plugins/archive/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.0</version>
		<name>archive</name>
		<title>Archive</title>
		<author>grommunio</author>
		<authorURL>https://grommunio.com</authorURL>
		<description>The archive plugin adds a button to the top menu bar that opens grommunio Archive inside grommunio Web</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<optional/>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.archive.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/archive.js</clientfile>
					<clientfile load="debug">js/archive-debug.js</clientfile>
					<clientfile load="source">js/ArchivePlugin.js</clientfile>
					<clientfile load="source">js/ui/ContentPanel.js</clientfile>
					<clientfile load="source">js/ui/Panel.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/archive.css</resourcefile>
					<resourcefile load="debug">resources/css/archive.css</resourcefile>
					<resourcefile load="source">resources/css/archive.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>
